[server]
port = 8080
secret_key = "SUPERSECRETSIGNKEY"
cookie_domain = "localhost"
cookie_secure = false

[db]
connection_string = "host=localhost port=5432 user=vulcanito_test dbname=vulcanito_test password=vulcanito_test sslmode=disable"
log_mode = true

[saml]
saml_metadata = "http://localhost:8083/simplesaml/saml2/idp/metadata.php"
saml_issuer = ""
saml_callback = "http://localhost:8080/api/v1/login/callback"
saml_trusted_domains = ["localhost"]

[defaults]
owners = []

[scanengine]
url = "http://localhost:8081/v1/"

[scheduler]
url = "http://localhost:8082/"
# Minimum period time in minutes that a program can be scheduled to run
minimum_interval = 30

[reports]
sns_arn = "arn:aws:sns:eu-west-1:test:test"

[awscatalogue]
kind = "None"
url = "https://catalogue.example.com"
key = "a key"
retries = 4
retry_interval = 2 # seconds
